spring:
  application:
    name: eureka-server
server:
  port: 1111
eureka:
  instance:
    hostname: eureka-service-1
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka-service-2:1112/eureka/