spring:
  application:
    name: eureka-server
server:
  port: 1112
eureka:
  instance:
    hostname: eureka-service-2
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka-service-1:1111/eureka